export default (plugin) => {
      plugin.useClickCounter()
        .useBadge()
        .useBreadcrumbs()
        .useBox()
        .useButton()
        .useCard()
        .useCarousel()
        .useCharacterCounter()
        .useCheckbox()
        .useChip()
        .useCollapsible()
        .useCollection()
        .useColors()
        .useDatePicker()
        .useDropdown()
        .useFab()
        .useFile()
        .useFooter()
        .useInput()
        .useModal()
        .useNavbar()
        .usePagination()
        .useParallax()
        .useProgress()
        .usePushpin()
        .useRadio()
        .useRange()
        .useScrollfire()
        .useScrollSpy()
        .useSelect()
        .useSidenav()
        .useSlider()
        .useSwitch()
        .useTabs()
        .useTooltip()
        .useTransitions()
        .useWaves()
        .useWell();

        const resources = [
          'shared/collapse-panel', 
          'shared/markdown', 
          'shared/logger', 
          'shared/sampleValueConverters'
        ];  

        config.globalResources(resources);     
    }